---
- hosts: servers
  become: true
  become_user: root

  tasks:
    - name: Update apt repo and cache on Debian based servers
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required 

  #  - name: Reboot the box if kernel updated
  #    reboot:
  #     msg: "Reboot initiated by Ansible for kernel updates"
  #      connect_timeout: 5
  #      reboot_timeout: 300
  #      pre_reboot_delay: 0
  #      post_reboot_delay: 30
  #      test_command: uptime
  #    when: reboot_required_file.stat.exists


    - name: check packages for updates on RHEL based servers
      shell: yum list updates | awk 'f;/Updated Packages/{f=1;}' | awk '{ print $1 }'
      changed_when: updates.stdout_lines | length > 0
      args:
        warn: false
      register: updates

    - name: display count
      debug:
        msg: "Found {{ updates.stdout_lines | length }} packages to be updated:\n\n{{ updates.stdout }}"
      when: updates.stdout_lines | length > 0

    - block:
        - name: install updates using yum
          yum:
            name: "*"
            state: latest

        - name: "check if reboot is required"
          shell: needs-restarting -r
          failed_when: false
          register: reboot_required
          changed_when: false
          when: updates.stdout_lines | length > 0 and reboot_required.rc != 0




